main: de.miraculixx.halloweench.Loader
name: MUtils-Halloween
version: 1.0
website: https://mutils.net
author: Miraculixx
api-version: 1.18

libraries:
  - "commons-codec:commons-codec:1.15"
  - "dev.jorel:commandapi-bukkit-shade:9.2.0"
  - "dev.jorel:commandapi-bukkit-kotlin:9.2.0"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.10"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.0-Beta"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.0-Beta"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0"
  - "org.yaml:snakeyaml:1.33"